spring.application.name=spring-boot-library

spring.datasource.url=jdbc:postgresql://localhost:5432/reactlibrarydatabase
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.data.rest.base-path=/api

okta.oauth2.client-id=0oai6u0n8aXssPu845d7
okta.oauth2.issuer=https://dev-06834739.okta.com/oauth2/default

